config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :rentals
  root "cars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :retals
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def new
    @car = Car.new
  end

  def create
      @car = Car.new(car_params)
      if @car.save
        redirect_to cars_path
      end
  end
end
  def index
    @cars = Car.all
  end

private

  def find_car
    @car = Car.find_by(id: params[:id])
    unless @car
     redirect_to root_path
     flash[:danger] = "Car not found"
   end
  end

  def car_params
    params.require(:car).permit :price_per_day, :price_per_km
  end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @rental = Rental.new
  end

  def show
    @rental = Rental.find_by id: params[:id]
  end

  def create
    @rental = Rental.new rental_params
    if @rental.save
      redirect_to @rental
    end
  end

  private

  def rental_params
    params.require(:rental).permit :car_id, :start_date, :end_date, :distance
  end

  def find_car
    @rental = Rental.find_by id: params[:id]
    @car = @rental.car
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/cars/index.html.erb
<% @cars = Car.all %>
<div class="row row-30 row-md-50 row-xl-70">
  <%= link_to "rent",new_rental_path %>
  <% @cars.each do |car| %>
  <div class="col-sm-6 col-lg-4 wow fadeIn">
    price per day : <%= car.price_per_day %>
    price per km : <%= car.price_per_km %>
  </div>
    <% end %>
</div>

app/views/cars/new.html.erb
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@car) do |f| %>

    <%= f.label :price_per_day %>
    <%= f.text_field :price_per_day, class: 'form-control' %>
    <%= f.label :price_per_km %>
    <%= f.text_field :price_per_km, class: 'form-control' %>
    <%= f.submit "Create car", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>

app/views/cars/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="csrf-token" content="cjDPjJqs4e9mdAH3MUaJVTcCQTdDi5QTMCpRxh5n">
<title> Anh Van</title>
<meta name="description" content="">
<meta name="twitter:card" content="">
<meta name="twitter:site" content="TopCV">
<meta name="twitter:title" content="">
<meta name="twitter:description" content="">
<meta name="robots" content="noindex">

<meta property="og:locale" content="vi_VN" />
<meta property="og:locale:alternate" content="en_US" />
<meta name="og:description" content="">
<meta name="og:site_name" content="TopCV">
<meta name="og:type" content="product">
<meta property="og:image" content="https://www.topcv.vn/images/cv-online-thumb-new.png">

<link rel="stylesheet" href="/packages/cvo/base/reset.css">
<link rel="stylesheet" href="/packages/cvo/base/style.css?v=2.6">
<link rel="stylesheet" href="/packages/cvo/base/print.css">
<link rel="stylesheet" href="/css/font-awesome.min.css">
<link rel="stylesheet" href="/cv-new/css/app.css?v=2.1.4">
<link rel="stylesheet" href="https://www.topcv.vn/cv-new/css/cv-viewer.css?v=2.1.4">
<link id="cv-scheme-css" rel="stylesheet" href="https://www.topcv.vn/packages/cvo/templates//impressive_3/colors/479b9d.css?v=2.3.3">
<link id="cv-font" rel="stylesheet" href="https://www.topcv.vn/packages/cvo/templates//impressive_3/fonts/default.css?v=2.1.1">
<link id="cv-font-size-css" rel="stylesheet" href="https://www.topcv.vn/packages/cvo/templates//impressive_3/font-sizes/font_normal.css?v=2.1.1">
<link id="cv-spacing-css" rel="stylesheet" href="https://www.topcv.vn/packages/cvo/templates//impressive_3/spacing/spacing_normal.css?v=2.1.1">

</head>
<body id="cv-viewer" class=" ">


<div class="btn-download-cv" data-id="BgVWCVFeVABQVQNfVwZdUQVcBQUEBg9fDwNSBg0150" data-name="Nguyen Anh Van">
<i class="fa fa-download"></i>
</div>
</div>
<div id="cv-layout-viewer">
<div id="cvo-document-root">
<div id="cvo-document" class="cvo-document">
<div class="cvo-page">
<div class="cvo-subpage">
<div id="cvo-body">
<div id="group-header">
<div class="cvo-col-9">
<div id="cvo-profile-fullname-wraper">
<span id="cvo-profile-fullname">Nguyen Anh Van</span>
</div>
<div id="cvo-profile-title-wraper">
<span id="cvo-profile-title">Ruby Development</span>
</div>
</div>
<div class="cvo-col-3">
<div id="cvo-profile-avatar-wraper" class="profile-item">
<img id="cvo-profile-avatar" src="https://static.topcv.vn/avatars/F9ObN8eiTZKUI0oALspS_611e76d854aae_cvtpl.jpg?1630759056" value="F9ObN8eiTZKUI0oALspS_611e76d854aae_cvtpl.jpg" alt="avatar">
</div>
</div>
</div>
<div id="line-seperate"></div>
<div class="cvo-col-5">
<div id="group-left">
<div id="cvo-profile" class="cvo-block">
<div class="cvo-block-header">
<span id="cvo-profile-blocktitle">Contact information</span>
</div>
<div class="contact-item">
<div class="contact-item-label">Date of birth</div>
<span id="cvo-profile-dob">Nov 15, 1994</span>
</div>
<div class="contact-item">
<div class="contact-item-label">Gender</div>
<span id="cvo-profile-gender">Male</span>
</div>
<div class="contact-item">
<div class="contact-item-label">Phone</div>
<span id="cvo-profile-phone">0349714696</span>
</div>
<div class="contact-item">
<div class="contact-item-label">Email</div>
<span id="cvo-profile-email">nguyenanhvan1511@gmail.com</span>
</div>
<div class="contact-item">
<div class="contact-item-label">Address</div>
<span id="cvo-profile-address">CT1 Sudico, Ha Noi</span>
</div>
<div class="contact-item">
<div class="contact-item-label">Website</div>
<span id="cvo-profile-website"><a href="https://www.facebook.com/profile.php?id=100013499528197" target="_blank" class="cvo-clickable-link">https://www.facebook.com/profile.php?id=100013499528197</a></span>
</div>
</div>
<div id="cvo-objective" class="cvo-block">
<div class="cvo-block-header">
<span id="cvo-objective-blocktitle">Objective</span>
</div>
<div class="cvo-block-body">
<div id="cvo-objective-objective">- <b>Short-term:</b> Become a Ruby development/Web development profestional<br />- <b>Long-term:</b> Become a fullstack development in Web development<br /></div>
</div>
</div> <div id="cvo-skillrate" class="cvo-block">
<div class="cvo-block-header"><span id="cvo-skillrate-blocktitle">Skills</span></div>
<div id="skillrate-table" class="cvo-block-body">
<div class="row">
<div><span class="cvo-skillrate-title">Ruby</span></div>
<div class="cvo-skillrate-bar" bval="4" rate-value="4">
<span class="cvo-skillrate-value"></span>
</div>
</div>
<div class="row">
<div><span class="cvo-skillrate-title">HTML & CSS</span></div>
<div class="cvo-skillrate-bar" bval="3" rate-value="3">
<span class="cvo-skillrate-value"></span>
</div>
</div>
<div class="row">
<div><span class="cvo-skillrate-title">English</span></div>
<div class="cvo-skillrate-bar" bval="3" rate-value="3">
<span class="cvo-skillrate-value"></span>
</div>
</div>
</div>
</div>
<div id="cvo-certification" class="cvo-block">
<div class="cvo-block-header"><span id="cvo-certification-blocktitle">Certifications</span></div>
<div id="certification-table" class="cvo-block-body">
<div class="row ">
<hr>
<div class="cvo-certification-title-wraper">
<span class="cvo-certification-title"><b>AWESOME ACADEMY</b> | Ruby development (Sun-asterisk)</span>
</div>
<div class="cvo-certification-time-wraper">
<div class="cvo-time-transparent">
<span class="cvo-certification-time">2014</span>
</div>
</div>
<div style="clear:both;"></div>
</div>
</div>
<div style="clear: both"></div>
</div>
<div id="cvo-interest" class="cvo-block">
<div class="cvo-block-header"><span id="cvo-interest-blocktitle">Interests</span></div>
<ul id="interest-table" class="cvo-block-body">
<li class="row"><span class="cvo-interest-details">Soccer, Game, Music</span></li>
<li class="row"><span class="cvo-interest-details">Reading</span></li>
</ul>
<div style="clear: both"></div>
</div>
</div>
</div>
<div class="cvo-col-7">
<div id="group-right">
<div id="cvo-experience" class="cvo-block">
<div class="cvo-block-header">
<span id="cvo-experience-blocktitle">Work experience</span>
</div>
<div id="experience-table" class="cvo-block-body">
<div class="row ">
<hr>
<div class="cvo-experience-time">
<span class="time-background">
<span class="cvo-experience-start">June 2019</span>
-
<span class="cvo-experience-end">2020</span>
</span>
</div>
<div class="cvo-experience-company-wraper">
<span class="cvo-experience-company">AWESOME ACADEMY (Sun-asterisk)</span>
</div>
<div><span class="cvo-experience-position">Development</span></div>
<div class="cvo-experience-details"><b>FOOD AND DRINK WEBSITES<br /></b>- <b>Github:</b> <a href="https://github.com/awesome-academy/pr1903_food_and_drinkbr-" target="_blank" class="cvo-clickable-link" rel="noreferrer noopener">https://github.com/awesome-academy/pr1903_food_and_drink<br />-</a> <b>Description:</b> FOOD AND DRINK is a process in which one can order various foods and beverages from local restaurant through the use of internet, just by sitting at home or any place<br />- <b>Technical stack:</b> Ruby on Rails, Javascript, HTML&amp;CSS<br /></div>
</div>
<div class="row ">
<hr>
<div class="cvo-experience-time">
<span class="time-background">
<span class="cvo-experience-start">Nov 2019</span>
-
<span class="cvo-experience-end">Jun 2020</span>
</span>
</div>
<div class="cvo-experience-company-wraper">
<span class="cvo-experience-company">AWESOME ACADEMY (Sun-asterisk)</span>
</div>
<div><span class="cvo-experience-position">Development</span></div>
<div class="cvo-experience-details"><b>TRAINING SYSTEMS WEBSITES</b><br /><b>- Github: </b><a href="https://github.com/awesome-academy/pr_1903_07_training_systembr-" target="_blank" class="cvo-clickable-link" rel="noreferrer noopener">https://github.com/awesome-academy/pr_1903_07_training_system<br />-</a> <b>Description:</b> TRAINING SYSTEMS specializes in all phases of online training systems and full web development<br />- <b>Technical stack:</b> Ruby on Rails, Javascript, HTML&amp;CSS<br /></div>
</div>
</div>
</div>
<div id="cvo-education" class="cvo-block">
<div class="cvo-block-header">
<span id="cvo-education-blocktitle">Education</span>
</div>
<div id="education-table" class="cvo-block-body">
<div class="row ">
<hr>
<div class="cvo-education-time">
<span class="time-background">
<span class="cvo-education-start">Oct 2013</span>
- <span class="cvo-education-end">May 2017</span>
</span>
</div>
<div class="cvo-education-school-wraper">
<span class="cvo-education-school">National Economics University</span>
</div>
<div><span class="cvo-education-title">Major: Economics</span></div>
<div class="cvo-education-details">GPA: 3.0/4</div>
</div>
<div class="row ">
<hr>
<div class="cvo-education-time">
<span class="time-background">
<span class="cvo-education-start">Oct 2019</span>
- <span class="cvo-education-end">May 2020</span>
</span>
</div>
 <div class="cvo-education-school-wraper">
<span class="cvo-education-school">AWESOME ACADEMY | (Sun-asterisk)</span>
</div>
<div><span class="cvo-education-title">Major: Ruby development</span></div>
<div class="cvo-education-details">GPA: 3.6/4</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</p>
</div>
</div>

<ul>
</ul>
</div>
</div>
</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drivy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/_form.html.erb
<% @cars = Car.all %>
<%= form_for(@rental) do |f| %>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.datetime_select :start_date, :ampm => true, :minute_step => 15 %>
  </div>
   <div class="field">
    <%= f.label :end_date %>
    <%= f.datetime_select :end_date, :ampm => true, :minute_step => 15 %>
  </div>
  <div class="field">
    <%= f.label :distance %>
    <%= f.text_field :distance, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <%= f.label :car %>
     <span>
      <%= f.select :car_id, @cars.map { |c| [c.price_per_km, c.price_per_day, c.id] },
        prompt: "select car" %>
    </span>
  </div>

  <div class="field mt-3">
    <%= f.submit "submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rentals/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h4 class="text-center">rent a car</h4>
  </div>
  <div class="col-md-12">
      <%= render "form" %>
  </div>
</div>

app/views/rentals/show.html.erb
<%= @rental.distance*@rental.car.price_per_km %>